api {
  web_server: https://app.clear.ml/
  api_server: https://api.clear.ml
  files_server: https://files.clear.ml
  credentials {
    access_key: "PPK8DJHOIOZ0GK5CPEW2UM2FQDLZ9Q"
    secret_key: "A300KvcKiif2IdGX1gf9pKo1-kthyLS2wkp8y8C8bmtDjszoWdJOMic9SyvedPD1XXs"
  }
}
